### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [ITHelpDec/CPP-Concurrency-in-Action#1]
.

**Comment by ITHelpDec** [comment]
Thanks, Dunk Master - do you have a link to the example and I’ll look to correcting it?

**Comment by Dunk-Master** [comment]
Thanks for quick response.
Can you see the godbolt link?

**Comment by ITHelpDec** [comment]
No problem at all.

Yes, I can see it - I was just wondering if it was a godbolt link I had created on my portfolio or if it related to a hazard_pointer .cpp I had created.

I can have a look through my repo, but if you have a link to hand then I’ll happily take a look through it to add corrections / request a PR.

**Comment by Dunk-Master** [comment]
chapter 7 - hazardly-explained_pointers.cpp
the link to your code in godbolt - https://godbolt.org/z/axejz6T5h

**Comment by Dunk-Master** [comment]
No solution yet  :-(

**Comment by Dunk-Master** [comment]
![886a79f2abed7e2d68e88ac44a2dfdba](https://github.com/ITHelpDec/CPP-Concurrency-in-Action/assets/126705166/36542083-6ad6-4346-b21c-576f9f4e597c)

**Comment by Dunk-Master** [comment]
did you find a solution?

**Comment by Dunk-Master** [comment]
i kinda need it for deadline homework

**Comment by ITHelpDec** [comment]
Hmm...I'm going to close this issue for now, as you appear to have a habit of posting issues then removing your posting activity and replacing the title with a `.`.

The solution to your initial problem involves passing the right compilation arguments (in this case, `lpthread`) - using this, we catch a runtime exception (I've supplied a Godbolt link [here](https://godbolt.org/z/W9d6GavKb), and the resources I used to resolve it are [here](https://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux), [here](https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking) and [here](https://web.archive.org/web/20180627210132/webpages.charter.net/ppluzhnikov/linker.html)).

Hope this helps you with your homework.

---
For other's reading this in the future, the messages received from Dunk-Master were.

```
https://godbolt.org/z/axejz6T5h
hazard pointer example does not work
```
```
Thanks for quick response.
Can you see the godbolt link?
```
```
chapter 7 - hazardly-explained-pointers.cpp
the link to your code in godbolt - https://godbolt.org/z/axejz6T5h
```
```
No solution yet :-(
```
```
did you find a solution?
```
```
I kinda need it for deadline homework
```
